# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-11-14 16:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todolist', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='todowork',
            name='list_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='todowork',
            name='created_on',
            field=models.DateField(auto_now_add=True, null=True),
        ),
    ]
